// AUTOMATICALLY GENERATED CLASS 11 BOTANY LECTURE DATABASE
// PRIMARY SOURCE OF TRUTH: OFFICIAL PHYSICS WALLAH PRACHAND NEET 2025 CLASS 11 BOTANY PLAYLIST
// PLAYLIST ID: PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT
// GENERATED BY src/scripts/syncBotany11.ts

export interface Botany11LectureRecord {
  youtubeId: string;
  title: string;
  thumbnail: string;
  duration: string;
  publishedAt: string;
  playlistIndex: number;
  embedUrl: string;
  watchUrl: string;
  teacher: string;
  channel: string;
  playlistId: string;
  playlistName: string;
  verified: boolean;
  chapterId: string;
  chapterName: string;
  topicId: string;
  unitName: string;
}

export const BOTANY_11_PLAYLIST_ID = "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT";
export const BOTANY_11_PLAYLIST_URL = "https://youtube.com/playlist?list=PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT";

export const BOTANY_11_LECTURE_DATABASE: Botany11LectureRecord[] = [
  {
    "youtubeId": "UnlG0wCuXx0",
    "title": "CELL - THE UNIT OF LIFE in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/UnlG0wCuXx0/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 1,
    "embedUrl": "https://www.youtube-nocookie.com/embed/UnlG0wCuXx0",
    "watchUrl": "https://www.youtube.com/watch?v=UnlG0wCuXx0",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-cell",
    "chapterName": "Chapter 6: Cell: The Unit of Life",
    "topicId": "topic-chap-bio-cell",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "HflKdigHpvI",
    "title": "CELL CYCLE AND DIVISION in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/HflKdigHpvI/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 2,
    "embedUrl": "https://www.youtube-nocookie.com/embed/HflKdigHpvI",
    "watchUrl": "https://www.youtube.com/watch?v=HflKdigHpvI",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-cell-cycle",
    "chapterName": "Chapter 7: Cell Cycle and Cell Division",
    "topicId": "topic-chap-bio-cell-cycle",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "W-85AKQ51Vg",
    "title": "BIOLOGICAL CLASSIFICATION in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/W-85AKQ51Vg/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 3,
    "embedUrl": "https://www.youtube-nocookie.com/embed/W-85AKQ51Vg",
    "watchUrl": "https://www.youtube.com/watch?v=W-85AKQ51Vg",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-biological-class",
    "chapterName": "Chapter 2: Biological Classification",
    "topicId": "topic-chap-bio-biological-class",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "vde2AZxr6Cw",
    "title": "PLANT KINGDOM in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/vde2AZxr6Cw/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 4,
    "embedUrl": "https://www.youtube-nocookie.com/embed/vde2AZxr6Cw",
    "watchUrl": "https://www.youtube.com/watch?v=vde2AZxr6Cw",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-plant-kingdom",
    "chapterName": "Chapter 3: Plant Kingdom",
    "topicId": "topic-chap-bio-plant-kingdom",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "NmwR6lweffc",
    "title": "ANATOMY OF FLOWERING PLANTS in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/NmwR6lweffc/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 5,
    "embedUrl": "https://www.youtube-nocookie.com/embed/NmwR6lweffc",
    "watchUrl": "https://www.youtube.com/watch?v=NmwR6lweffc",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-anatomy",
    "chapterName": "Chapter 5: Anatomy of Flowering Plants",
    "topicId": "topic-chap-bio-anatomy",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "axI_jcIzE0U",
    "title": "PHOTOSYNTHESIS IN HIGHER PLANTS in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/axI_jcIzE0U/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 6,
    "embedUrl": "https://www.youtube-nocookie.com/embed/axI_jcIzE0U",
    "watchUrl": "https://www.youtube.com/watch?v=axI_jcIzE0U",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-photosynthesis",
    "chapterName": "Chapter 8: Photosynthesis in Higher Plants",
    "topicId": "topic-chap-bio-photosynthesis",
    "unitName": "Plant Physiology"
  },
  {
    "youtubeId": "Nn-KiCDiT3M",
    "title": "PLANT GROWTH & DEVELOPMENT in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/Nn-KiCDiT3M/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 7,
    "embedUrl": "https://www.youtube-nocookie.com/embed/Nn-KiCDiT3M",
    "watchUrl": "https://www.youtube.com/watch?v=Nn-KiCDiT3M",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-plant-growth",
    "chapterName": "Chapter 10: Plant Growth and Development",
    "topicId": "topic-chap-bio-plant-growth",
    "unitName": "Plant Physiology"
  },
  {
    "youtubeId": "TPkkSJvkwQU",
    "title": "RESPIRATION IN PLANTS in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/TPkkSJvkwQU/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 8,
    "embedUrl": "https://www.youtube-nocookie.com/embed/TPkkSJvkwQU",
    "watchUrl": "https://www.youtube.com/watch?v=TPkkSJvkwQU",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-respiration",
    "chapterName": "Chapter 9: Respiration in Plants",
    "topicId": "topic-chap-bio-respiration",
    "unitName": "Plant Physiology"
  },
  {
    "youtubeId": "75CsrOPRXVM",
    "title": "MORPHOLOGY OF FLOWERING PLANTS in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/75CsrOPRXVM/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 9,
    "embedUrl": "https://www.youtube-nocookie.com/embed/75CsrOPRXVM",
    "watchUrl": "https://www.youtube.com/watch?v=75CsrOPRXVM",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-morphology",
    "chapterName": "Chapter 4: Morphology of Flowering Plants",
    "topicId": "topic-chap-bio-morphology",
    "unitName": "Diversity of Living Organisms"
  },
  {
    "youtubeId": "GGDGm152XVE",
    "title": "THE LIVING WORLD in 1 Shot || All Concepts & PYQs Covered || Prachand NEET",
    "thumbnail": "https://i.ytimg.com/vi/GGDGm152XVE/hqdefault.jpg",
    "duration": "4-6 hours",
    "publishedAt": "2026-07-31T12:47:37.733Z",
    "playlistIndex": 10,
    "embedUrl": "https://www.youtube-nocookie.com/embed/GGDGm152XVE",
    "watchUrl": "https://www.youtube.com/watch?v=GGDGm152XVE",
    "teacher": "Vipin Sir",
    "channel": "Competition Wallah",
    "playlistId": "PL8_1l_iSLgySfHitIh57GRljVNsOJjYyT",
    "playlistName": "Complete Class 11th BOTANY in One Shot | Prachand NEET 2025",
    "verified": true,
    "chapterId": "chap-bio-living-world",
    "chapterName": "Chapter 1: The Living World",
    "topicId": "topic-chap-bio-living-world",
    "unitName": "Diversity of Living Organisms"
  }
];

export const BOTANY_11_AUDIT_REPORT = {
  playlistVideosFound: 10,
  importedVideos: 10,
  playableVideos: 10,
  embedVerified: 10,
  failedVideos: 0,
  rejectedVideos: 0,
  mappedChapters: 10,
  mappedTopics: 10,
  coveragePercent: Math.round((10 / 10) * 100),
  brokenYoutubeIds: [],
  missingChapters: [],
  missingTopics: []
};
